### ISSUE TITLE
Fehler auf Produktivsystem (getRouteParams)

### ISSUE THREAD

**Issue by mtrojan-ub** [ubtue/tuefind#1902]
Unklar beim Aufruf welcher Unterseite es genau auftritt, allerdings gibt es im Serverlog relativ viele Einträge nach folgendem Muster:
`
[Thu Nov 25 10:35:57.676163 2021] [proxy_fcgi:error] [pid 2109970:tid 140167415273216] [client 79.194.117.34:50600] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Call to a member function getParams() on null in /usr/local/vufind/module/TueFind/src/TueFind/View/Helper/TueFind/TueFind.php:124\nStack trace:\n#0 /usr/local/vufind/themes/tuefind/templates/search/searchTabs.phtml(2): TueFind\\View\\Helper\\TueFind\\TueFind->getRouteParams()\n#1 /usr/local/vufind/vendor/laminas/laminas-view/src/Renderer/PhpRenderer.php(505): include('/usr/local/vufi...')\n#2 /usr/local/vufind/module/VuFind/src/VuFind/View/Helper/Root/Context.php(102): Laminas\\View\\Renderer\\PhpRenderer->render(NULL)\n#3 /usr/local/vufind/themes/ixtheo/templates/search/searchbox.phtml(70): VuFind\\View\\Helper\\Root\\Context->renderInContext('search/searchTa...', Array)\n#4 /usr/local/vufind/vendor/laminas/laminas-view/src/Renderer/PhpRenderer.php(505): include('/usr/local/vufi...')\n#5 /usr/local/vufind/themes/ixtheo/templates/layout/layout.phtml(180): Laminas\\View\\Renderer\\PhpRenderer->render(NULL)\n#6 /usr/local/vufind/vendor/laminas/laminas-view/src/Renderer/PhpRenderer.p...\n'`

Wir wissen dass es sich um einen Bug handelt und wie man ihn behebt, allerdings ist unklar welche URL man genau aufrufen muss um ihn zu reproduzieren.

Da wir die Liveserver aufgrund der laufenden 7.1 nicht auf herkömmlichem Wege pullen können, bereiten wir einen Hotfix vor.

**Comment by mtrojan-ub** [comment]
Der fix hierzu wurde nun erstmal auf ptah eingespielt. Wir warten noch etwas ab ob es dort Seiteneffekte gibt, bevor wir den Hotfix produktiv einspielen.

**Comment by mtrojan-ub** [comment]
Heute mit den Serverwartungen ist auch der fix live gegangen. Wir werden das Produktivsystem (insb. die Logs) noch ein paar Tage beobachten, bevor wir den Issue schließen.

**Comment by mtrojan-ub** [comment]
Der Fehler tritt auf dem Produktivsystem nicht mehr auf, daher schließe ich den Issue.
